services:
  app:
    build: .
    image: debug-ruby-rails
    ports:
      - "3001:3000"
    volumes:
      - ".:/app"
    environment:
      RUBY_DEBUG_NO_RELINE: true
      RUBY_DEBUG_HOST: 0.0.0.0
      RUBY_DEBUG_PORT: 12345
